# Generated by Django 3.0.3 on 2020-08-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_auto_20200804_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/cat.jpg', upload_to='product_pics'),
        ),
    ]
