# Generated by Django 3.0.3 on 2020-08-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='cat.jpg', upload_to='product_pics'),
        ),
    ]
