# Generated by Django 3.0.3 on 2020-08-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_auto_20200804_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
    ]
